jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            KnpPaginatorBundle:
                namespace_prefix: Knp\Bundle\PaginatorBundle
                path: '%kernel.project_dir%/config/packages/serializer/KnpPaginatorBundle'
            KnpPager:
                namespace_prefix: Knp\Component\Pager
                path: '%kernel.project_dir%/config/packages/serializer/KnpPager'

