<?php


namespace App\Tests\integration\Controller;


use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class OrderControllerTest extends WebTestCase
{
    private ?Client $client;

    protected function setUp()
    {
        $this->client = new Client();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated
        $this->client = null;
    }

    public function testGetOrders()
    {
        try {
            $response = $this->client->get('http://localhost:8000/api/orders', []);
        } catch (GuzzleException $e) {
            //TODO: this exception should be handled
            var_dump($e->getMessage());
            die();
        }

        self::assertEquals(200, $response->getStatusCode());

        $orders = $response->getBody()->getContents();
        self::assertCount(5, json_decode($orders));

        //TODO: add more assertions
    }
}